### ISSUE TITLE
Delay Monad using sized types for ISetoids

### ISSUE THREAD

**Issue by ElessarWebb** [copumpkin/categories#18]
I've been constructing some categorical stuff using this library.
One of these constructions is the delay monad using sized types in the category `Categories.Agda.ISetoids`.
For now it is part of an external development; but if you are interested I could prepare a PR.

Let me know and thanks for all the proofs!

**Comment by JacquesCarette** [comment]
Please do submit a PR. I will review it for potential inclusion.

**Comment by ElessarWebb** [comment]
I noticed that my formalization isn't so useful at the moment; I'll get back to this if I have something better.
