### ISSUE TITLE
in stdlib-0.16 implicit argument of Lift is now explicit

### ISSUE THREAD

**Issue by p-pavel** [copumpkin/categories#21]
Categories/Lift.agda & Categories/Support/Equivalence.agda are affected

**Comment by JacquesCarette** [comment]
I would certainly welcome PRs for these things!

**Comment by p-pavel** [comment]
This is a breaking change -- it will break compatibility with the older versions of stdlib. 

Probably it will be nice to have a new branch? 

Anyway, I'm trying to fix all the issues I've reported (or at least investigate on them) and I'll issue PR after that. in the case of Lift it's simple but see above about compatibility concerns.

**Comment by JacquesCarette** [comment]
I think most people upgrade their Agda versions.  But certainly documenting the commit version of the version that works with stdlib-0.15 is worthwhile. I guess maybe even make an official release or something [not that I quite know how, yet].  A clear README is likely in order too.

**Comment by JacquesCarette** [comment]
This library is now obsolete - and the newer version of the library has this problem fixed.
